<?php
global $hospital_name_arr;

$hospital_name_arr['01'] = '中山大学肿瘤防治中心';
$hospital_name_arr['02'] = '中山大学第一附属医院';
$hospital_name_arr['03'] = '中山大学第二附属医院';
$hospital_name_arr['04'] = '中山大学第三附属医院';
$hospital_name_arr['05'] = '中山大学第六附属医院';
$hospital_name_arr['06'] = '广东省人民医院';
$hospital_name_arr['07'] = '南方医科大学南方医院';
$hospital_name_arr['08'] = '佛山市第一人民医院';
$hospital_name_arr['09'] = '深圳市人民医院';
$hospital_name_arr['10'] = '梅州市人民医院';
$hospital_name_arr['11'] = '汕头大学第一附属医院';
$hospital_name_arr['12'] = '汕头市中心医院';
$hospital_name_arr['13'] = '福建省肿瘤医院';
$hospital_name_arr['14'] = '厦门市第一人民医院';
$hospital_name_arr['15'] = '广东省中医院';
$hospital_name_arr['16'] = '广州医学院第一附属医院';
$hospital_name_arr['17'] = '暨南大学第一附属医院';
$hospital_name_arr['18'] = '潮州市中心医院';
$hospital_name_arr['19'] = '广东药学院第一附属医院';
$hospital_name_arr['20'] = '清远人民医院';
$hospital_name_arr['21'] = '粤北人民医院';
$hospital_name_arr['22'] = '英德人民医院';
$hospital_name_arr['23'] = '中山大学第五附属医院';
$hospital_name_arr['24'] = '广州医学院第三附属医院';
$hospital_name_arr['25'] = '中山市人民医院';
