<?php

include_once dirname(__FILE__) . '/include/form_elements.inc';

include_once dirname(__FILE__) . '/include/crf_case.conf.inc';

include_once dirname(__FILE__) . '/include/crf_dataset.inc';

/**
 * CRF Dataset Table Name
 */
define('CRF_DS_TABLE', 'crf_case_data');


/**
* Implementation of hook_menu
*/
function crf_case_menu()
{
  $items = array();
  $items['crf_case/%/%'] = array(
    'page callback' => 'crf_case',
    'page arguments' => array(1,2),
    'access callback' => 'crf_case_perm',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK
  );
  $items['crf_case_edit'] = array(
    'page callback' => 'crf_case_edit',
    'access callback' => 'crf_case_perm',
    'type' => MENU_CALLBACK
  );
  return $items;  
}

function crf_case_perm() {
  global $user;
  if ((isset($user->roles[3]) || $user->uid == 1)) {
    return true;
  }
  else {
    return false;
  }
}

function crf_case($p_uid, $type) {
  global $user;
  $hospital_no = $user->profile_hospital_no;
  $hospital_name = $user->profile_hospital_name;
  $query = "SELECT p_uid FROM apply WHERE p_uid = %d AND hospital_no = '%s' AND hospital_name = '%s'";
  if (db_result(db_query($query, $p_uid, $hospital_no, $hospital_name))) {
    crf_common_session('p_uid', $p_uid);
    crf_common_session('type', $type); //1代表可编辑 2代表不可编辑
    drupal_goto('crf_case_edit');
  }
  else {
    drupal_set_message('非法操作，请从下列列表中选择一项进入录入!');
    drupal_goto('crf_case');
  }
}

/**
 * 参数eg:
 * crf_case_edit/zqtys
 * crf_case_edit/第几页
 */
function crf_case_edit() {
  $no = arg(1);
  if (empty($no)) {
    $no = 'zhiqing_tys';
  }
  
  if (FALSE === get_form_elements_arr($no)) {
    drupal_set_message('未建立的数组元素,请联系管理员！');
    return drupal_not_found();
  }
  
  return drupal_get_form("crf_case_form", $no);
}

function crf_case_form(&$form_state, $arg = NULL) {
  $no = $arg;
  $form_elements_arr = get_form_elements_arr($no);
  
  $dataset = crf_ds_load($no);
  $dataset = json_to_array($dataset);
  
  foreach($form_elements_arr as $row => $group) {
    if (stristr($row, '#') === FALSE) {//skip #
      foreach($group as $element_no => $element) {
  //      print "e_{$no}_{$row}_{$element_no}";
        crf_set_element_default_value($element, $dataset, $row, $element_no);
        $form["e_{$no}_{$row}_{$element_no}"] = $element;
      }
    }
  }
  
  $form['#theme'] = 'crf_case_form_'. $no;
  $form['submit'] = array(
    '#type' => 'submit',
    '#value'=> '确定'
  );
  return $form;
}


function crf_case_form_submit($form, $form_state) {
  $no = arg(1);
  if (empty($no)) {
    $no = 'zhiqing_tys';
  }
  
  $values  = $form_state['values'];
  $dataset = crf_ds_parse($no, $values, $form);
  
  //var_dump($dataset);
  /**
   * $dataset
   *  array
       1 => array (
          1 => string '2012-06-05 00:00:00' (length=19)
          2 => string '2012-06-05 00:00:00' (length=19)
       )
  */
   
   $hook = "crf_ds_update_$no";
   if (is_callable($hook)) {
     $dataset = call_user_func_array($hook, array($no, $dataset));
   }
   
   crf_ds_save($dataset, $no);
}


function crf_set_element_default_value(&$element, $dataset, $row, $col) {
  if (isset($dataset[$row]) && isset($dataset[$row][$col])) {
    $element['#default_value'] = $dataset[$row][$col];
  }
} 


/**
 * Implementation of hook_theme().
 */
function crf_case_theme() {
  return array(
    'crf_case_form_zhiqing_tys' => array(
      'arguments' => array('form' => NULL, 'class' => 'zhiqing_tys'),
      'template' => 'templates/zhiqing-tys',
    ),
    'crf_case_form_ruxuan_bz' => array(
      'arguments' => array('form' => NULL, 'class' => 'ruxuan-bz'),
      'template' => 'templates/ruxuan-bz',
    ),
  );
}

function json_to_array($web){
  $arr=array();
  
  foreach($web as $k=>$w){
    if(is_object($w)) {
      $arr[$k]=json_to_array($w); //判断类型是不是object
    }
    else {
      $arr[$k]=$w;
    }
  }
  
  return $arr;
}