<?php
global $hospital_name;

$hospital_name['01'] = '中山大学肿瘤防治中心';
$hospital_name['02'] = '中山大学第一附属医院';
$hospital_name['03'] = '中山大学第二附属医院';
$hospital_name['04'] = '中山大学第三附属医院';
$hospital_name['05'] = '中山大学第六附属医院';
$hospital_name['06'] = '广东省人民医院';
$hospital_name['07'] = '南方医科大学南方医院';
$hospital_name['08'] = '佛山市第一人民医院';
$hospital_name['09'] = '深圳市人民医院';
$hospital_name['10'] = '梅州市人民医院';
$hospital_name['11'] = '汕头大学第一附属医院';
$hospital_name['12'] = '汕头市中心医院';
$hospital_name['13'] = '福建省肿瘤医院';
$hospital_name['14'] = '厦门市第一人民医院';
$hospital_name['15'] = '广东省中医院';
$hospital_name['16'] = '广州医学院第一附属医院';
$hospital_name['17'] = '暨南大学第一附属医院';
$hospital_name['18'] = '潮州市中心医院';
$hospital_name['19'] = '广东药学院第一附属医院';
$hospital_name['20'] = '清远人民医院';
$hospital_name['21'] = '粤北人民医院';
$hospital_name['22'] = '英德人民医院';