<?php
function crf_common_init() {
  global $user;
  $profile =  profile_load_profile($user);  
}
/**
* Implementation of hook_menu
*/
function crf_common_menu()
{
  $items = array();
  $items['crf_front'] = array(
    'title' => 'Front',
    'page callback' => 'crf_common_front',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
   $items['crf_export'] = array(
    'title' => '随机列表',
    'page callback' => 'crf_common_export',
    //'access callback' => 'crf_work_checkperm',
    'access arguments' => array('crf view list'),
    'type' => MENU_CALLBACK
  );
  return $items;  
}


function crf_common_export() {
  //header("Content-type:application/csv"); 
  //header("Content-Disposition:\"inline;filename=data.csv\""); 
  
  header('Content-Encoding: UTF-8');
  header('Content-type: text/csv; charset=UTF-8');
  header("Content-Disposition: attachment; filename=export.csv");
  echo "\xEF\xBB\xBF"; // UTF-8 BOM

  crf_common_export_do();
}

function crf_common_export_do() {
  global $crf_el_name;
  //$crf_el_name['dyxx'];
  
  $header[] = 'uid';
  $header_data = array();
  
  foreach ($crf_el_name as $name => $data) {
    foreach ($data as $key => &$val) {
      foreach ($val as $k => &$v) {
        $tt = $name . '-' . $v['name'];
        $header[] = $tt;
        $header_data[$tt] = $v['value']; 
        //print $v['name'] . ' ,';
      }
    }
  }
  
  //print_r($header);
  //exit;
  $body = array();
  
  $sql = 'SELECT * FROM crf_case_data WHERE name = "%s" ';
  if ($uids = crf_common_session('search_result')) {
    if (count($uids)) {
      $sql .= ' AND uid in ( ' . join(',', $uids) . ')';
    }
  }
  
  $res = db_query($sql, 'dyxx');
  while ($row = db_fetch_array($res)) {
    $item   = array();
    $item[] = $row['uid'];
    
    crf_common_set_data($header, $item, $row, $header_data);
    $body[] = $item;
  }
  
  //array_unshift($body, $header);
  echo array_to_scv($body, $header);
}

function crf_common_set_data(&$header, &$item, &$row, &$header_data) {
  $data = json_to_array(json_decode($row['data']));
  $uid  = $row['uid'];
  
  $all  = array(
    'dyxx' => $data, 
    'sf_1' => json_to_array(crf_ds_load('sf_1', $uid)), 
    'sf_2' => json_to_array(crf_ds_load('sf_2', $uid)), 
    'sf_3' => json_to_array(crf_ds_load('sf_3', $uid)), 
    'sf_4' => json_to_array(crf_ds_load('sf_4', $uid)), 
    'sf_5' => json_to_array(crf_ds_load('sf_5', $uid)), 
  );
          
  foreach ($header as $pos => $h) {
    if (in_array($h, array('uid')))      
      continue;
    
    list ($no, $field) = explode('-', $h, 2);
    $keys = crf_search_name_to_key($field, $no);
    if (isset($all[$keys[0]])) {
      $current = $all[$keys[0]];
    //var_dump($keys, $h, $data[$keys[1]][$keys[2]]);
      $current_val = $current[$keys[1]][$keys[2]];
      
      $item[$pos] = _export_deal_value($field, $current_val, $keys, $header_data[$h]);
    }
  }
}

function _export_deal_value($field, $val, $keys, $header_data) {
  global $crf_el;
  
  if ($keys) {
    if (   isset($crf_el[$keys[0]])
        && isset($crf_el[$keys[0]][$keys[1]])
        && isset($crf_el[$keys[0]][$keys[1]][$keys[2]])
       ) {
      $el = $crf_el[$keys[0]][$keys[1]][$keys[2]];
      if ($el['#type'] == 'checkboxes') {
        $val = _export_deal_get_checkbox($header_data, $val);
        if (empty($val)) $val = '无';
      }
      if ($el['#type'] == 'radios') {
        $val = _export_deal_get_radios($header_data, $val);
        if (empty($val)) $val = '无';
      }
    }
  }
  
  switch ($field) {
    case '性别':
      return $val == 0 ?  '男' : '女';
    case '姓名缩写':
        return strtoupper($val);
    default :
      return $val;
  }
}

function _export_deal_get_radios($header_data, $val) {
  $r = array();
  if (!$val) return $r;
  
  $header_data = array_flip($header_data);
  
  if (is_array($val)) {
    foreach($val as $k => $v) {
      $r[] = $header_data[$val];
    }
  }
  else {
    $r[] = $header_data[$val];
  }
  
  return $r;
}

function _export_deal_get_checkbox($header_data, $val) {
  $r = array();
  if (!$val) return $r;
  
  $header_data = array_flip($header_data);
  
  if (is_array($val)) {
    foreach($val as $k => $v) {
      $r[] = $header_data[$val];
    }
  }
  else {
    $r[] = $header_data[$val];
  }
  
  return $r;
}
/**
* Generatting CSV formatted string from an array.
* By Sergey Gurevich.
*/
function array_to_scv($array, $header_row = null, $col_sep = ",", $row_sep = "\n", $qut = '"')
{
  
	if (!is_array($array) or !is_array($array[0])) return false;
	
	//Header row.
	if ($header_row)
	{
		foreach ($header_row as $key => $val)
		{
      $val = str_replace('dyxx-', '', $val);
      $val = str_replace('sf', '随访', $val);
			//Escaping quotes.
			$key = str_replace($qut, "'", $val);
			$output .= "$col_sep$qut$key$qut";
		}
		$output = substr($output, 1)."\n";
	}
  
	//Data rows.
	foreach ($array as $key => $val)
	{
		$tmp = '';
		foreach ($val as $cell_key => $cell_val)
		{
      if (is_array($cell_val)) $cell_val = join(' ', $cell_val);
			//Escaping quotes.
			$cell_val = str_replace($qut, "'", $cell_val);
			$tmp .= "$col_sep$qut$cell_val$qut";
		}
		$output .= substr($tmp, 1).$row_sep;
	}
	
	return $output;
}

/**
 * Menu callback; Generate a listing of promoted nodes.
 */
function crf_common_front() {
  global $user;
  if ($user->uid) {
    drupal_goto('crf_list');
  }
  else {
    drupal_set_title('');
    $output = drupal_get_form('user_login_block');    
  }
  return $output;
}

function crf_common_session($key, $value = null) {  
  if (isset($value)) {    
    unset($_SESSION['crf'][$key]);    
    $_SESSION['crf'][$key] = $value;  
  }    
  if (isset($_SESSION['crf'][$key])) {    
    return $_SESSION['crf'][$key];  
  }
  return FALSE;
}

function crf_common_user($op, &$edit, &$account, $category = NULL) {
  
  switch ($op) {
    case 'login': 
      $_GET['destination'] = 'crf_list';
      drupal_goto('crf_list');
      break;
  }
}

function crf_common_perm() {
  return array('crf view all', 'crf view list', 'crf case view', 'crf case edit',);
}

function crf_common_form_alter() {
  
}