<?php
module_load_include('inc', 'crf_common', 'include/crf_common.conf');
/**
* Implementation of hook_menu
*/
function crf_work_menu()
{
  $items = array();
  $items['crf_add'] = array(
    'title' => '随机申请表',
    'page callback' => 'crf_work_add',
    'access callback' => 'crf_work_checkperm',
    'type' => MENU_CALLBACK
  );
  $items['crf_list'] = array(
    'title' => '随机列表',
    'page callback' => 'crf_work_list',
    //'access callback' => 'crf_work_checkperm',
    'access arguments' => array('crf view list'),
    'type' => MENU_CALLBACK
  );
  $items['crf_search'] = array(
    'title' => '条件搜索',
    'page callback' => 'crf_work_search',
    //'access callback' => 'crf_work_checkperm',
    'access arguments' => array('crf view list'),
    'type' => MENU_CALLBACK
  );
  $items['patient'] = array(
    'title' => '随机操作结果',
    'page callback' => 'crf_patient',
    'access callback' => 'crf_work_checkperm',
    'type' => MENU_CALLBACK
  );
  return $items;  
}

function crf_work_checkperm() {
  global $user;
  if ((isset($user->roles[3]) || $user->uid == 1)) {
    return true;
  }
  else {
    return false;
  }
}

function crf_work_add() {
  unset($_SESSION['crf']);
  drupal_goto('crf_case_edit/dyxx');
}

function crf_work_alloc_rand($alloc = FALSE) {
  global $hospital_name_arr, $user;
  $hospital_name = $hospital_name_arr[$user->profile_hospital_no];
  
  $array = FALSE;
  
  //固定PUID
  $query = 'SELECT * FROM apply_rand WHERE hospital = "%s" AND used = 0 AND rand_type = "R" LIMIT 1';
  $array = db_fetch_array(db_query($query, $hospital_name));
  if ($array) {
    if ($array['group_before'] == '1') {
      $array['group'] = 'A';
    }
    else {
      $array['group'] = 'B';
    }
  }
  
  //是否阻止继续录入，如果R的没有完成
  $block_new_without_spec = TRUE;
  if ($block_new_without_spec && !$array) {
    $query = 'SELECT * FROM apply_rand WHERE used = 0 AND rand_type = "R" LIMIT 1';
    $next  = db_fetch_array(db_query($query));
    if ($next) {
      drupal_set_message('目前为已入组用户阶段，需把已入组用户录入完毕！ 接下来应为：' . $next['hospital'] . '。');
      return FALSE;
    }
  }
  //END 阻止
  
  //随机PUID
  if (!$array) {
    
    //获取已有BLOCK
    $query = 'SELECT * FROM apply_rand WHERE hospital = "%s" AND used = 0 AND rand_type = "L" LIMIT 1';
    $array = db_fetch_array(db_query($query, $hospital_name));
   
    
    if (!$array) {
      //分配新BLOCK
      $query = 'SELECT * FROM apply_rand WHERE used = 0 AND puid > 132 AND rand_type <> "R" AND rand_type <> "L" LIMIT 1';
      $array = db_fetch_array(db_query($query));

      if (!$array) {
        $query = 'SELECT * FROM apply_rand WHERE used = 0 AND puid > 32 AND puid < 81 AND rand_type <> "R" AND rand_type <> "L" LIMIT 1';
        $array = db_fetch_array(db_query($query));
      }
      
      if ($alloc && $array) {
        $query = 'UPDATE apply_rand SET hospital = "%s", rand_type = "L" WHERE `block` = %d';
        db_query($query, $hospital_name, $array['block']);
      }
    }
  }
  
  if ($array && $alloc) {
    $query = 'UPDATE apply_rand SET used = 1 WHERE puid = %d';
    db_query($query, $array['puid']);
  }
  
  return $array;
}

function crf_work_add_form(&$form_state) {
  global $user;
  global $hospital_name_arr;
  $form = array();
  $form['hospital_no'] = array(
    '#type' => 'item',
    '#title' => '试验中心编号（自动生成）',
    '#value' => $user->profile_hospital_no,
  );
  $form['hospital_name'] = array(
    '#type' => 'item',
    '#title' => '试验中心名称（自动生成）',
    '#value' => $hospital_name_arr[$user->profile_hospital_no],
  );
  /*$form['sift'] = array(
    '#type' => 'textfield',
    '#title' => '筛选号',
    '#size' => 15,
    '#maxlength' => 3,
    '#default_value' => ''
  );*/
  
  $form['u_name'] = array(
    '#type' => 'textfield',
    '#size' => 15,
    '#maxlength' => 4,  
    '#title' => '患者姓名',
    '#default_value' => '',
    '#description' => '患者姓名请填写中文。'
  );
  $form['p_name'] = array(
    '#type' => 'textfield',
    '#size' => 15,
    '#maxlength' => 4,  
    '#title' => '受试者姓名缩写',
    '#default_value' => '',
    '#description' => '患者姓名拼音缩写需填满四格，两字姓名分填两字前两个字母，三字姓名填前两字首字母与第三字前两个字母，四字姓名填每字首字母。'
  );
//  $form['p_birthday'] = array(
//    '#type' => 'date_popup',
//    '#date_format' => 'Y-m-d',
//    '#date_year_range' => '-90:+0',
//    '#size' => 15,
//    '#title' => '受试者出生日期',
//  );
  $form['u_age'] = array(
    '#type' => 'textfield',
    '#size' => 15,
    '#maxlength' => 3,  
    '#title' => '患者年龄',
    '#default_value' => '',
    '#description' => '请输入患者年龄!'
  );
  $form['case_history_no'] = array(
    '#type' => 'textfield',
    '#title' => '病历号',
    '#size' => 15,
    '#default_value' => ''
  );
  $form['u_gender'] = array(
    '#type' => 'radios',
    '#title' => '受试者的性别',
    '#options' => array('男','女'),
  );
  $form['editor'] = array(
    '#type' => 'textfield',
    '#title' => '研究医生签名',
    '#default_value' => '',
    '#size' => 15
  );
  $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => '手机号码',
    '#default_value' => '',
    '#size' => 15,
    '#maxlength' => 11, 
    '#description' => '请填写你的手机号码，以便及时通知患者随访信息，更好管理患者。本系统保证不会将您的手机号码用于本研究以外的任何用途。'
  );
  $form['u_phone'] = array(
    '#type' => 'textfield',
    '#title' => '用户手机号码',
    '#default_value' => '',
    '#size' => 15,
    '#maxlength' => 11, 
    '#description' => '请填写手机号码。'
  );
  $form['u_card_id'] = array(
    '#type' => 'textfield',
    '#title' => '受试者身份证号码',
    '#default_value' => '',
    '#size' => 55,
    '#maxlength' => 25, 
    '#description' => '请填写受试者身份证号。'
  );
  $form['u_weight'] = array(
    '#type' => 'textfield',
    '#title' => '受试者体重(KG)',
    '#default_value' => '',
    '#size' => 15,
    '#description' => '请填写受试者体重。'
  );
  $form['u_address'] = array(
    '#type' => 'textfield',
    '#title' => '受试者家庭住址',
    '#default_value' => '',
    '#size' => 105,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value'=> '确定'
  );

  return $form;
}

function crf_work_add_form_validate($form, &$form_state) {
//  if (empty($form_state['values']['sift'])) {
//    form_set_error('sift', '筛选号不能为空!');
//  }
//  else if (3 != mb_strlen($form_state['values']['sift']) || !is_numeric($form_state['values']['sift'])){
//    form_set_error('sift', '筛选号必须为3位数字!');
//  }
  if (empty($form_state['values']['p_name'])) {
    form_set_error('p_name', '受试者姓名缩写不能为空!');
  }
  else if (4 != mb_strlen($form_state['values']['p_name']) || !ctype_alpha($form_state['values']['p_name'])){
    form_set_error('p_name', '受试者姓名缩写请用四个字母表示，两字姓名分填两字前两个字母，三字姓名填前两字首字母与第三字前两个字母，四字姓名填每字首字母！');
  }
  if (empty($form_state['values']['u_name'])) {
    form_set_error('u_name', '受试者姓名不能为空!');
  }
  if (empty($form_state['values']['u_address'])) {
    form_set_error('u_address', '受试者住址不能为空!');
  }
//  if (empty($form_state['values']['p_birthday'])) {
//    form_set_error('p_birthday', '受试者出生日期不能为空!');
//  }
  if (empty($form_state['values']['case_history_no'])) {
    form_set_error('case_history_no', '病历号不能为空!');
  }
  if (!ctype_alnum($form_state['values']['case_history_no'])) {
    form_set_error('case_history_no', '病历号只能为数字和字母!');
  }
  if ($form_state['values']['u_gender'] == '') {
    form_set_error('u_gender', '受试者性别需要选择一项!');
  }
  if (empty($form_state['values']['u_age'])) {
    form_set_error('u_weight', '患者年龄不能为空!');
  }
  if (!is_numeric($form_state['values']['u_age'])) {
    form_set_error('u_age', "患者年龄必须数字！");
  }
  if (empty($form_state['values']['u_weight'])) {
    form_set_error('u_weight', '受试者体重不能为空!');
  }
  if (strlen($form_state['values']['u_weight']) != 3 && strlen($form_state['values']['u_weight']) != 2) {
    form_set_error('u_weight', "受试者体重必须为2位或者3位！");
  }
  if ($form_state['values']['u_weight'] > 150) {
    form_set_error('u_weight', "受试者体重请输入合理的体重！");
  }
  if (empty($form_state['values']['editor'])) {
    form_set_error('editor', '研究医生签名不能为空!');
  }
  if (!preg_match("/[\x{4e00}-\x{9fa5}]+/u", $form_state['values']['editor'], $match)) {
    form_set_error('editor', '研究医生签名必须为汉字!');
  }
  if (!preg_match("/[\x{4e00}-\x{9fa5}]+/u", $form_state['values']['u_name'], $match)) {
    form_set_error('u_name', '受试者姓名必须为汉字!');
  }
  if (empty($form_state['values']['phone'])) {
    form_set_error('phone', '手机号不能为空!');
  }
  else if (11 != mb_strlen($form_state['values']['phone']) || !is_numeric($form_state['values']['phone'])){
    form_set_error('phone', '手机号必须为11位数字!');
  }  
  if (empty($form_state['values']['u_phone'])) {
    form_set_error('u_phone', '受试者手机号不能为空!');
  }
  else if (11 != mb_strlen($form_state['values']['u_phone']) || !is_numeric($form_state['values']['u_phone'])){
    form_set_error('u_phone', '受试者手机号必须为11位数字!');
  }
  if (empty($form_state['values']['u_card_id'])) {
    form_set_error('u_card_id', '受试者身份证号不能为空!');
  }
  else if (18 != mb_strlen($form_state['values']['u_card_id'])){
    form_set_error('u_card_id', '受试者身份证号必须为18位!');
  }
}

function crf_work_add_form_submit($form, &$form_state) {
  global $hospital_name_arr, $user;
  $hospital_name = $hospital_name_arr[$user->profile_hospital_no];
  
//  $rand = crf_work_alloc_rand(TRUE);
  
//  if ($rand) {
//    
//  }
//  else {
//    drupal_set_message('随机号码分配失败，请联系管理员！', 'error');
//    //drupal_goto();
//    return;
//  }
  
  $obj->p_uid = $rand['puid'];
  $obj->hospital_no = $user->profile_hospital_no;
  $obj->p_name = $form_state['values']['p_name'];
  $obj->p_birthday = substr($form_state['values']['p_birthday'], 0, 10);
  $obj->case_history_no = $form_state['values']['case_history_no'];
  $obj->approved = $form_state['values']['approved'];
  $obj->approved_time = substr($form_state['values']['approved_time'], 0, 10);
  $obj->team = $rand['group'] == 'A' ? '1' : '2';
  $obj->apply_time = date("Y-m-d H:i:s");
  $obj->editor = $form_state['values']['editor'];
  $obj->phone = $form_state['values']['phone'];
  $obj->u_address = $form_state['values']['u_address'];
  $obj->u_phone = $form_state['values']['u_phone'];
  $obj->u_card_id = $form_state['values']['u_card_id'];
  $obj->u_name = $form_state['values']['u_name'];
  $obj->u_gender = $form_state['values']['u_gender'];
  $obj->u_age = $form_state['values']['u_age'];
  $obj->u_weight = $form_state['values']['u_weight'];
  
  $table = 'apply';
  $r = crf_work_write_record($table, $obj);
    
  if ($r != FALSE) {
    $p_uid = db_last_insert_id($table, 'p_uid');
    $team = get_rand_team($p_uid);
    $query = 'UPDATE ' . $table . ' SET team = %d WHERE p_uid = %d';
    db_query($query, $team, $p_uid);
    drupal_set_message('添加成功！');
    drupal_goto('patient/' . $p_uid);
  }
}

function crf_work_write_record($table, $obj) {
//  $query = 'INSERT INTO '. $table .' (hospital_no, sift, p_name, p_birthday, case_history_no, approved, approved_time, team, apply_time, editor) VALUES("%s", "%s", "%s", "%s", "%s", %d, "%s", %d, "%s", "%s")';
//  $query = 'INSERT INTO '. $table .' (p_uid, hospital_no, p_name, p_birthday, case_history_no, approved, approved_time, team, apply_time, editor, phone, u_name, u_card_id, u_weight, u_age, u_gender, u_phone, u_address) VALUES(%d, "%s", "%s", "%s", "%s", %d, "%s", %d, "%s", "%s", "%s", "%s", "%s", %d, %d, %d, "%s", "%s")';
  $query = 'INSERT INTO '. $table .' (p_uid, hospital_no, p_name, p_birthday, case_history_no, approved, approved_time, team, apply_time, editor, phone, u_address, u_phone, u_card_id, u_name, u_gender, u_age, u_weight) VALUES(%d, "%s", "%s", "%s", "%s", %d, "%s", %d, "%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s")';
  $arr = (array)$obj;
  $r = db_query($query, $arr);
  return $r;
}

function get_rand_team($p_uid) {
  $arr = array('1' => '1', '2' => '2', '3' => '1', '4' => '2', '5' => '2', '6' => '1', '7' => '1', '8' => '2', '9' => '2', '0' => '1');
  $n = substr($p_uid, -1);
  return $arr[$n];
}

function crf_work_search() {
  drupal_set_breadcrumb(array(l('首页', ''),'条件搜索'));
  if (TRUE || user_access('crf view all')) {
    $output .= drupal_get_form('crf_search_user_form');
  }
  if ($_SESSION['crf']['search_result'] == "") {
    return $output;
  }
  global $user;
  global $hospital_name_arr;
  global $pager_page_array;

  $genders[0] = "男";
  $genders[1] = "女";
  
  $sfs[0] = "是";
  $sfs[1] = "否";
  
  $hospital_name_current = $user->profile_hospital_no;
  if (user_access('crf view all') && $hospital_key = crf_common_session('hospital_key')) {
    $hospital_name_current = $hospital_key;
  }
  
  $limit  = 20;
  
  $terms = taxonomy_get_tree(1);
  foreach($terms as $k => $v) {
    $term_arr[$v->tid] = $v->name;
  }

//  $header = array(array('data'=>'序号', 'field'=>'p_uid', 'sort'=>'asc'), '姓名', '姓名缩写', '性别', '年龄', '体重', '联系电话', '研究医生', '是否接受统一随访', '信息录入');
  $header = array('序号', '姓名', '姓名缩写', '性别', '年龄', '体重', '联系电话', '研究医生', '是否接受统一随访', '信息录入');
  
  $rows = array();
//  print_r($_SESSION['crf']);
//  print $search_p_uid;
  $search_p_uid = implode(',', $_SESSION['crf']['search_result']);
//  print_r($user);
  if (_is_special() == TRUE) {
    $results = pager_query("SELECT * FROM crf_case_data WHERE name='dyxx' AND hospital_no != '' AND uid in ($search_p_uid)" . tablesort_sql($header), $limit);
  }
  else {
    $results = pager_query("SELECT * FROM crf_case_data WHERE name='dyxx' AND hospital_no = $hospital_name_current  AND uid in ($search_p_uid)" . tablesort_sql($header), $limit);
  }
//  print "SELECT * FROM crf_case_data WHERE name='dyxx' AND hospital_no = $hospital_name_current  AND p_uid in ($search_p_uid)" . tablesort_sql($header);

  $pager_current = $pager_page_array[0] + 1;
  
  $start = ($pager_current - 1) * $limit ;
  
  $user_arr = _get_user_arr();
  while ($r = db_fetch_object($results)) {
    $data = $r->data;
    $data = json_decode($data);
    $d = json_to_array($data);
    $rows[] = array(
      sprintf('%03s', ++$start),
      $d[1][1],
      $d[1][2],
      $genders[$d[1][4]],
      $d[1][3],
      $d[3][2],
      $d[2][2],
      $d[32][1], 
      $sfs[$d[31][1]], 
      l('进入', 'crf_case/'. $r->uid .'/1')
    );
   }
  if (count($rows) == 0) {
    $output.= "<h3 style='color:red'>无搜索记录，请检查搜索条件！</h3>";
    return $output;
  }
  $output .= "[<b>中心编号：</b> <i>{$hospital_name_current}</i>  <b>中心名称：</b> <i>{$hospital_name_arr[$hospital_name_current]}</i>]";
  $output .= theme('table', $header, $rows);
  $output .= theme('pager', $limit);
  $output.= "<div style=float:right>". l('导出搜索结果', 'crf_export') ."</div>";
  return $output;
}

function crf_search_user_form() {
  global $search_i;
  $name_list = array('' => ' -请选择- ', 'dyxx' => '调研信息','sf_1'=>'第一次随访','sf_2'=>'第二次随访','sf_3'=>'第三次随访','sf_4'=>'第四次随访','sf_5'=>'第五次随访');
  $search = crf_common_session('search');
//  print_r($_SESSION);
  for ($i = 1;$i<=$search_i;$i++) {
    $form['name_'.$i] = array(
      '#type'  => 'select',
      '#title' => '选择分类',
      '#default_value' => $search[$i]['name'],
      '#options' => $name_list,
      '#description' => '选择一个分类'
    );
    $form['key_'.$i] = array(
      '#type'  => 'textfield',
      '#title' => '搜索名称',
      '#size' => '20',
      '#default_value' => $search[$i]['key'],
      '#description' => '输入搜索名称，如性别'
    );
//    print $_REQUEST['key_'. $i];exit;
    $form['val_'.$i] = array(
      '#type'  => 'textfield',
      '#title' => '取值',
      '#size' => '20',
      '#default_value' => $search[$i]['val'],
      '#description' => '根据搜索的名称输入一个值，如搜索名称为性别，在这里输入男或者女，如未填写，则判断此处是否有值'
    );
  }
  $form['#theme'] = 'crf_search';
  $form['submit'] = array(
   '#type' => 'submit',
   '#value'=> '确定'
  );
  $form['info'] = array(
   '#type' => 'item',
   '#value'=> '如有资料修改，请重新提交搜索条件。'
  );
  return $form;
  
}

function crf_search_user_form_validate($form, &$form_state) {
  global $search_i;
  for ($i = 1;$i<=$search_i;$i++) {
    if ($form_state['values']['name_1'] == "") {
      form_set_error('name_1', '请至少选择一个分类!');
    }
    if ($form_state['values']['key_'.$i] != '' && $form_state['values']['name_'.$i] == "") {
      form_set_error('name_'.$i, '请选择分类!');
    }
    if ($form_state['values']['key_'.$i] == '' && $form_state['values']['name_'.$i] != "") {
      form_set_error('key_'.$i, '请填写搜索名称，如性别!');
    }
  }
//  print_r($form_state);exit;  
}

function crf_search_user_form_submit($form, &$form_state) {
  if ($form_state['submitted'] == 1) {
    global $search_i;
    for ($i=1;$i<=$search_i;$i++) {
      if ($form_state['values']["key_$i"] != "") {
        $search[$i]['name'] = $form_state['values']["name_$i"];
        $search[$i]['key'] = $form_state['values']["key_$i"];
        $search[$i]['val'] = $form_state['values']["val_$i"];
      }
      else {
        break;
      }
    }
    $search = crf_search_el_key($search);
    crf_common_session('search', $search);
  }
  $search = crf_common_session('search');
  global $user;
  $result = array();
  if (_is_special() == TRUE) {
    $res = db_query("SELECT * FROM crf_case_data WHERE hospital_no != '' ORDER BY uid");
  }
  else {
    $res = db_query("SELECT * FROM crf_case_data WHERE hospital_no = $user->profile_hospital_no ORDER BY uid");
  }
  while ($r = db_fetch_array($res)) {
    $result[$r['uid']][$r['name']] = json_to_array(json_decode($r['data']));
  }
  $search_result = crf_search_match($search, $result);
  crf_common_session('search_result', $search_result);
}

function crf_search_el_key($search) {
  global $crf_el_name;
  foreach ($search as $conds => $cond) {
    $key = $cond['key'];
    foreach($crf_el_name[$cond['name']] as $row => $group) {
      if (stristr($row, '#') === FALSE) {//skip #
        foreach($group as $element_no => $element) {
          if (preg_match("/.*$key.*/", $element['name'])) {
//            print $key.'--'.$element['name'].'---'.$row.' '.$element_no.'||||';
            $search[$conds]['position'] = array($row, $element_no);
            if ($element['value'] != "") {
              $search[$conds]['val_option'] = $element['value']; 
              $search[$conds]['val_r'] = $element['value'][$search[$conds]['val']]; 
            }
            break 2;
          }
        }
      }
    }
  }
  return $search;
}

function crf_search_match($search, $result) {
//  print_r($search);
//  print_r($result);exit;
  foreach($result as $p_uid => $names) {
    foreach($search as $k => $cond) {
      $current_val = $names[$cond['name']][$cond['position'][0]][$cond['position'][1]];
      if (is_null($current_val)) {
        unset($result[$p_uid]);
        break;
      }
      else {
        if ($cond['val_r'] !== null) {
          if ($cond['val_r'] != $current_val) {
            unset($result[$p_uid]);
            break;
          }
        }
        else {
          $cur_cond = $cond['val'];
          if (!preg_match("/.*$cur_cond.*/", $current_val)) {
            unset($result[$p_uid]);
            break;
          }
        }
      }
      unset($cur_cond);
      unset($current_val);
    }
  }
//  print_r($result);
  $search_result = array();
  foreach($result as $p_uid => $names) {
    $search_result[] = $p_uid;
  }
  return $search_result;
}

function crf_work_list() {
  drupal_set_breadcrumb(array(l('首页', ''),'随机列表'));
  global $user;
  global $hospital_name_arr;
  global $pager_page_array;

  $genders[0] = "男";
  $genders[1] = "女";
  
  $sfs[0] = "是";
  $sfs[1] = "否";
  
  $hospital_name_current = $user->profile_hospital_no;
  if (user_access('crf view all') && $hospital_key = crf_common_session('hospital_key')) {
    $hospital_name_current = $hospital_key;
  }
  
  $limit  = 20;
  
  $terms = taxonomy_get_tree(1);
  foreach($terms as $k => $v) {
    $term_arr[$v->tid] = $v->name;
  }

//  $header = array(array('data'=>'序号', 'field'=>'p_uid', 'sort'=>'asc'), '姓名', '姓名缩写', '性别', '年龄', '体重', '联系电话', '研究医生', '是否接受统一随访', '信息录入');
  $header = array('序号', '姓名', '姓名缩写', '性别', '年龄', '体重', '联系电话', '研究医生', '是否接受统一随访', '信息录入');
  
  $rows = array();

  if ($user->uid == 1) {
    $results = pager_query("SELECT * FROM crf_case_data WHERE name='dyxx' AND hospital_no != ''" . tablesort_sql($header), $limit);
  }
  else {
    $results = pager_query("SELECT * FROM crf_case_data WHERE name='dyxx' AND hospital_no = $hospital_name_current " . tablesort_sql($header), $limit);
  }
  

  $pager_current = $pager_page_array[0] + 1;
  
  $start = ($pager_current - 1) * $limit ;
  
  $user_arr = _get_user_arr();
  while ($r = db_fetch_object($results)) {
    $data = $r->data;
    $data = json_decode($data);
    $d = json_to_array($data);
    $rows[] = array(
      sprintf('%03s', ++$start),
      $d[1][1],
      $d[1][2],
      $genders[$d[1][4]],
      $d[1][3],
      $d[3][2],
      $d[2][2],
      $d[32][1], 
      $sfs[$d[31][1]], 
      l('进入', 'crf_case/'. $r->uid .'/1')
    );
   }

  if (user_access('crf view all')) {
    $output .= drupal_get_form('crf_select_hospital_form');
  }
  
  $output .= "[<b>中心编号：</b> <i>{$hospital_name_current}</i>  <b>中心名称：</b> <i>{$hospital_name_arr[$hospital_name_current]}</i>]";
  $output .= theme('table', $header, $rows);
  $output .= theme('pager', $limit);
  return $output;
}

function _add_serial_no($id) {
  
}

function crf_work_theme() {
  return array(
    'patient' => array(
      'arguments' => array('row' => NULL, 'team_arr' => array(), 'approved_arr' => array()),
      'template' => 'patient',
    ),
    'crf_search' => array(
      'arguments' => array('form' => NULL),
    ), 
  );
  
}

function theme_crf_search($form){
  global $search_i; 
  for ($i=1; $i<=$search_i; $i++) {
    $output.= "<div class=search_$i><span style=display:inline-block>". drupal_render($form["name_$i"]) ."</span> &nbsp;&nbsp;&nbsp;<span style=display:inline-block>". drupal_render($form["key_$i"]) ."</span> &nbsp;&nbsp;&nbsp;<span style=display:inline-block>". drupal_render($form["val_$i"]) ."</span></div>";  
  }
  $output.= drupal_render($form);
  return $output;
}

function _add_rand($str) {
  $str = '000'.$str;
  return 'R' . substr($str, -3);
}

function crf_patient() {
  $pid = arg(1);
  $row = db_fetch_array(db_query('SELECT * FROM apply WHERE p_uid = %d', $pid));
  
  $terms = taxonomy_get_tree(1);
  foreach($terms as $k => $v) {
    $term_arr[$v->tid] = $v->name;
  }
  $approved_arr = array('是','否');
  return theme('patient', $row, $term_arr, $approved_arr);
}

function crf_select_hospital_form() {
  global $hospital_name_arr;
   $hospital = crf_common_session('hospital_key');

   $form['hospital'] = array(
    '#type' => 'select',
    '#title' => '请选择要医院',
    '#default_value' => $hospital ? $hospital : '01',
    '#options' => $hospital_name_arr,
  );
  $form['submit'] = array(
   '#type' => 'submit',
   '#value'=> '确定'
  );
  return $form;
}

function crf_select_hospital_form_submit(&$form, &$form_state) {
  crf_common_session('hospital_key', $form_state['values']['hospital']);
}

function _get_user_arr() {
  $query = "SELECT uid, name FROM users";
  $result = db_query($query);
  while ($row = db_fetch_object($result)) {
    $arr[$row->uid] = $row->name;
  }
  return $arr;
}

function _is_special() {
  global $user;
  if ($user->uid == 1 || $user->roles[4] != "" || $user->roles[5] != "") {
    return TRUE;
  }
  else {
    return FALSE;
  }
}