<?php

/**
* Implementation of hook_menu
*/
function image_captcha_refresh_menu()
{
  $items = array();
  $items['image_captcha_refresh'] = array(
    'page callback' => 'image_captcha_captcha_refresh',  
    'access callback' => TRUE,   
    'type' => MENU_CALLBACK
  );
  return $items;  
}

/**
* Implementation of hook_form_alter
*/
function image_captcha_refresh_form_alter(&$form, $form_state, $form_id)
{
  if(Drupal.jsEnabled)
  {
    if(db_fetch_object(db_query("SELECT module FROM {captcha_points} WHERE form_id = '%s'", $form_id))->module == 'image_captcha')
    {
      drupal_add_js('$("#edit-captcha-response-wrapper").prepend(\'' . theme('captcha_refresh_template') . '\');
                     $(".captcha img").attr("id", "image-captcha-image")', 'inline', 'footer');
      drupal_add_js(array(
        'image_captcha' => array(
          'ajaxUrl' => url('image_captcha_refresh/', array('absolute'=>true)),
        ),
      ), 'setting');
      drupal_add_js('
      function change_image() {
        $.get(
          Drupal.settings.image_captcha.ajaxUrl 
          + $("input[@name=\'form_id\']").val() 
          + "/" 
          + $("input[@name=\'captcha_sid\']").val(),
          function(response) {
            $("#image-captcha-image").attr("src",response);
            $("#edit-captcha-sid").val(parseInt($("#edit-captcha-sid").val())+1);
            $("#edit-captcha-response").val("");
          }
        ); 
        return false;
      }
      ', 'inline');
    }
  }  
}

/**
 * menu callback function that refresh the CAPTCHA image
 */
function image_captcha_captcha_refresh($form_id, $captcha_token) {
  module_load_include('inc', 'captcha');
  $captcha_sid = _captcha_generate_captcha_session($form_id);
  $captcha = module_invoke('image_captcha', 'captcha', 'generate', 'Image', $captcha_sid);
  _captcha_update_captcha_session($captcha_sid, $captcha['solution']);
  preg_match('/src=[\'"]?([^\'" >]+)[\'" >]/', $captcha['form']['captcha_image']['#value'], $matches);
  echo $matches[1];
  exit;
}


/**
* Implementation of hook_theme
*/
function image_captcha_refresh_theme()
{
  return array(
    'captcha_refresh_template' => array(
      'arguments' => array(),
      'template' => 'captcha-refresh-template'
    ),
  );  
}

