<?php
global $hospital_name_arr;
global $search_i;

$search_i = 5;

$hospital_name_arr['01'] = '北京协和医院';
$hospital_name_arr['02'] = '北京人民医院';
$hospital_name_arr['03'] = '北京医院';
$hospital_name_arr['04'] = '北京中日友好医院';
$hospital_name_arr['05'] = '北京西苑医院';
$hospital_name_arr['06'] = '上海六院';
$hospital_name_arr['07'] = '上海市交通大学附属第六人民医院';
$hospital_name_arr['08'] = '上海交通大学医学院附属瑞金医院';
$hospital_name_arr['09'] = '上海中医药大学附属岳阳医院';
$hospital_name_arr['10'] = '上海交通大学医学院附属第九人民医院';
$hospital_name_arr['11'] = '上海复旦大学附属华东医院';
$hospital_name_arr['12'] = '上海复旦大学附属华山医院';
$hospital_name_arr['13'] = '上海申康中心附属奉贤中心医院';
$hospital_name_arr['14'] = '上海申康中心附属黄浦区中心医院';


