<?php

include_once dirname(__FILE__) . '/include/form_elements.inc';

include_once dirname(__FILE__) . '/include/crf_case.conf.inc';

include_once dirname(__FILE__) . '/include/crf_dataset.inc';

/**
 * CRF Dataset Table Name
 */
define('CRF_DS_TABLE', 'crf_case_data');


/**
* Implementation of hook_menu
*/
function crf_case_menu()
{
  $items = array();
  $items['crf_case/%/%'] = array(
    'page callback' => 'crf_case',
    'page arguments' => array(1,2),
    'access callback' => 'crf_case_checkperm',
    //'access arguments' => array(1),    
    //'access aguments' => array('crf case view'),
    'type' => MENU_CALLBACK
  );
  $items['crf_case_edit'] = array(
    'page callback' => 'crf_case_edit',
    //'access callback' => 'crf_case_checkperm',
    'access arguments' => array('crf case view'),
    'type' => MENU_CALLBACK
  );
  return $items;  
}

function crf_case_checkperm() {
  global $user;
  if ((isset($user->roles[3]) || $user->uid == 1)) {
    return true;
  }
  else if(user_access('crf case view') || user_access('crf view all') || user_access('crf case edit')) {
    return true;
  }
  else {
    return false;
  }
}

function crf_case($p_uid, $type) {
  global $user;
  //$hospital_no = $user->profile_hospital_no;
  //$query = "SELECT * FROM apply WHERE p_uid = %d AND hospital_no = '%s'";
  $query = "SELECT * FROM apply WHERE p_uid = %d";
  $result = db_query($query, $p_uid/*, $hospital_no*/);
  $p_arr = db_fetch_array($result);
//  print_r($p_arr);exit;
  if ($p_arr != NULL) {
    crf_common_session('p_arr', $p_arr);
    crf_common_session('p_uid', $p_uid);
    crf_common_session('type', $type); //1代表可编辑 2代表不可编辑
    drupal_goto('crf_case_edit');
  }
  else {
    drupal_set_message('非法操作，请从下列列表中选择一项进入录入!');
    drupal_goto('crf_case');
  }
}

/**
 * 参数eg:
 * crf_case_edit/zqtys
 * crf_case_edit/第几页
 */
function crf_case_edit() {
  $p_arr = crf_common_session('p_arr');
  
  drupal_set_breadcrumb(array(l('首页', ''), l('随机列表', 'crf_list'), '病历录入 【姓名缩写：' . $p_arr['p_name'] . '】'));
  $no = arg(1);
  if (empty($no)) {
    $no = 'zhiqing_tys';
    drupal_goto('crf_case_edit/' . $no);
    exit;
  }
  
  if (FALSE === get_form_elements_arr($no)) {
    drupal_set_message('未建立的数组元素,请联系管理员！');
    return drupal_not_found();
  }
  
   $disabled = crf_common_session('disable_item');
   if (is_array($disabled) && in_array($no, $disabled)) {
     //禁用了，则跳过
     $next = crf_get_next_form_key($no);
     drupal_goto('crf_case_edit/' . $next);
   }

   
  //crf_progress_save(arg(1));
  $row = crf_progress_load();

  if ($row && isset($row['data']) && !empty($row['data'])) {
    $progress = json_decode($row['data']);
    
    if (in_array('shiyan_sjc', $progress)) {
      drupal_add_js(array('all_doable' => 1), 'setting');
    }
    
    /*
    $last     = array_pop($progress);
    $next     = crf_get_next_form_key($last);
    $progress[] = $last;
    $progress[] = $next;
    if (!in_array($no, $progress)) {
      drupal_set_message('请按顺序填写前面没有完成的表格！', 'error');
      return ''; 
    }
    **/
  }
  else {
    //if ($no != 'zhiqing_tys') {
    //  drupal_set_message('请按顺序填写前面没有完成的表格！', 'error');
    //  return ''; 
    // }
    $progress = array();
  }
  
  drupal_add_js(array('progress' => $progress), 'setting');
  $disabled = crf_common_session('disable_item');
  if (is_array($disabled) && count($disabled)) {
     drupal_add_js(array('disabled' => $disabled), 'setting');
  }
  
  include_once dirname(__FILE__) . '/include/crf_validate.inc';
  return drupal_get_form("crf_case_form", $no);
}

function crf_case_form(&$form_state, $arg = NULL) {
  $no = $arg;
  $form_elements_arr = get_form_elements_arr($no);
  
  $dataset = crf_ds_load($no);
  $dataset = json_to_array($dataset);
  
  foreach($form_elements_arr as $row => $group) {
    if (stristr($row, '#') === FALSE) {//skip #
      foreach($group as $element_no => $element) {
        //print "e_{$no}_{$row}_{$element_no}";
        crf_set_element_default_value($element, $dataset, $row, $element_no);
        $form["e_{$no}_{$row}_{$element_no}"] = $element;
      }
    }
  }
  
  $form['#theme']    = 'crf_case_form_'. $no;
  $form['#validate'][] = 'crf_case_form_step_validate';


  $validate = "crf_case_validate_$no";
  if (is_callable($validate)) {
     $form['#validate'][] = $validate;
  }

  if (user_access('crf case edit')) {
    $no == 'yanjiu_js' ? $v = '完 成' : $v = '保 存 & 继 续';
    $form['submit'] = array(
      '#type' => 'submit',
      '#value'=> $v
    );
  }
  else {
    drupal_add_js('
     $(function(){
       $("input,select").attr("disabled", "disabled");
     });
    ', 'inline');
  }
  return $form;
}


function crf_case_form_step_validate($form, &$form_state) {
  $no = arg(1);
  //form_set_error('form', '保存顺序有问题，请按顺序填写表格！');

  if ( $no && $no != 'zhiqing_tys') {
    $prev     = crf_get_next_form_key($no, -1);
    $progress = crf_progress_load();

    if ($progress && $progress['data']) {
      $prog = json_decode($progress['data']);
      if (!in_array($prev, $prog)) {
//        form_set_error('form', '保存顺序有问题，请按顺序填写表格！');
      }
    }
  }
}

function crf_case_form_submit($form, $form_state) {
  $no = arg(1);
  if (empty($no)) {
    $no = 'zhiqing_tys';
  }
  
  
  $values  = $form_state['values'];
  $dataset = crf_ds_parse($no, $values, $form);
  
  //var_dump($dataset);
  /**
   * $dataset
   *  array
       1 => array (
          1 => string '2012-06-05 00:00:00' (length=19)
          2 => string '2012-06-05 00:00:00' (length=19)
       )
  */
   
   include_once dirname(__FILE__) . '/include/crf_form_save.inc';
   
   $hook = "crf_ds_update_$no";
   if (is_callable($hook)) {
     $dataset = call_user_func_array($hook, array($no, $dataset));
   }
   
   crf_ds_save($dataset, $no);
   crf_progress_save($no);
   
   $hook = "crf_form_save_$no";
   if (is_callable($hook)) {
     call_user_func_array($hook, array($dataset, $form_state));
   }
   
   drupal_set_message('保存成功！');
   
   $next = crf_get_next_form_key($no);
   
   if ($next !== FALSE) {
     drupal_goto('crf_case_edit/' . $next);
   }
   else {
     drupal_set_message('恭喜您录入已完成！');
   }
}


function crf_get_next_form_key($current, $offset = 1) {
   global $crf_el;
   $keys  = array_keys($crf_el);
   $index = array_search($current, $keys);
   
   if (FALSE !== $index && $keys[$index+$offset]) {
     return $keys[$index+$offset];
   }
   else {
     return FALSE;
   }
}

function crf_set_element_default_value(&$element, $dataset, $row, $col) {
  if (isset($dataset[$row]) && isset($dataset[$row][$col])) {
    $element['#default_value'] = $dataset[$row][$col];
  }
} 


function crf_progress_save($name) {
 
  $p_uid = crf_common_session('p_uid');
  $row   = crf_progress_load();
  $did   = FALSE;  
  
  if (!$row) {
    db_query("INSERT INTO crf_case_user_profile (uid, data, updated) VALUES (%d, '%s', %d)",  $p_uid, json_encode(array($name)), time());
    $did = TRUE;
  }
  else {
    $keys = json_decode($row['data']);
    
    if (!in_array($name, $keys)) {
      $keys[] = $name;
      db_query("UPDATE crf_case_user_profile SET data = '%s', updated = %d WHERE uid = %d", json_encode($keys), time(), $p_uid);
      $did = TRUE;
    }
  }
  
  if ($did) {
    crf_progress_load($p_uid, TRUE);
  }
}

function crf_progress_load($p_uid = NULL, $reset = FALSE) {
  static $p;
  if (!$p_uid) {
    $p_uid = crf_common_session('p_uid');
  }
  
  if (!isset($p[$p_uid]) || $reset) {
    $row = db_fetch_array(db_query('SELECT * FROM crf_case_user_profile WHERE uid = %d', $p_uid));
    $p[$p_uid] = $row;
  }
  
  return $p[$p_uid];
}

function json_to_array($data){
  $arr=array();
  if (empty ($data)) {
    return $arr;
  }
  
  if (is_object($data)) {
    $data = (array)$data;
  }
  
  foreach($data as $k=>$w){
    if(is_object($w)) {
      $arr[$k]=json_to_array($w); //判断类型是不是object
    }
    else {
      $arr[$k]=$w;
    }
  }
  
  return $arr;
}

function crf_case_init() {
  $path = drupal_get_path('module', 'crf_case');
  //drupal_add_css($path . '/js/jquery.mb.tooltip.1.6/css/mbtooltip.css', 'module');
  //  drupal_add_js($path . '/js/crf_common.js', 'module');
  //drupal_add_js($path . '/js/jquery-tooltip/js/jtip.js', 'module');
  drupal_add_js($path . '/js/vtip/vtip.js', 'module');
  drupal_add_css($path . '/js/vtip/css/vtip.css', 'module');

  drupal_add_js($path . '/js/crf_common.js', 'module');
}



/**
 * Implementation of hook_theme().
 */
function crf_case_theme() {
  return array(
    'crf_case_form_zhiqing_tys' => array(
      'arguments' => array('form' => NULL, 'class' => 'zhiqing-tys', 'table' => 'zhiqing_tys', 'table_name' => '知情同意书'),
      'template' => 'templates/zhiqing_tys',
    ),
    'crf_case_form_ruxuan_bz' => array(
      'arguments' => array('form' => NULL, 'class' => 'ruxuan-bz', 'table' => 'ruxuan_bz', 'table_name' => '入选标准'),
      'template' => 'templates/ruxuan_bz',
    ),
    'crf_case_form_paichu_bz' => array(
      'arguments' => array('form' => NULL, 'class' => 'paichu-bz', 'table' => 'paichu_bz', 'table_name' => '排除标准'),
      'template' => 'templates/paichu_bz',
    ),
    'crf_case_form_renkou_tjx' => array(
      'arguments' => array('form' => NULL, 'class' => 'renkou-tjx', 'table' => 'renkou_tjx', 'table_name' => '人口统计学'),
      'template' => 'templates/renkou_tjx',
    ),
    'crf_case_form_weiai_ssyzdqk' => array(
      'arguments' => array('form' => NULL, 'class' => 'weiai-ssyzdqk', 'table' => 'weiai_ssyzdqk', 'table_name' => '胃癌手术与诊断情况'),
      'template' => 'templates/weiai_ssyzdqk',
    ),
    'crf_case_form_jiwang_hxhjb' => array(
      'arguments' => array('form' => NULL, 'class' => 'jiwang-hxhjb', 'table' => 'jiwang_hxhjb', 'table_name' => '既往或现患疾病'),
      'template' => 'templates/jiwang_hxhjb',
    ),
    'crf_case_form_huaiyun_knx' => array(
      'arguments' => array('form' => NULL, 'class' => 'huaiyun-knx', 'table' => 'huaiyun_knx', 'table_name' => '怀孕可能性'),
      'template' => 'templates/huaiyun_knx',
    ),
    'crf_case_form_teshu_jc' => array(
      'arguments' => array('form' => NULL, 'class' => 'teshu-jc', 'table' => 'teshu_jc', 'table_name' => '特殊检查'),
      'template' => 'templates/teshu_jc',
    ),
    'crf_case_form_xindian_tjc' => array(
      'arguments' => array('form' => NULL, 'class' => 'xindian-tjc', 'table' => 'xindian_tjc', 'table_name' => '心电图检查'),
      'template' => 'templates/xindian_tjc',
    ),      
    'crf_case_form_quanshen_tgjc' => array(
      'arguments' => array('form' => NULL, 'class' => 'quanshen-tgjc', 'table' => 'quanshen_tgjc', 'table_name' => '全身体格检查'),
      'template' => 'templates/quanshen_tgjc',
    ),   
    'crf_case_form_xueqing_zlbzwjc' => array(
      'arguments' => array('form' => NULL, 'class' => 'xueqing-zlbzwjc', 'table' => 'xueqing_zlbzwjc', 'table_name' => '血清肿瘤标志物检测'),
      'template' => 'templates/xueqing_zlbzwjc',
    ),   
    'crf_case_form_shiyan_sjc' => array(
      'arguments' => array('form' => NULL, 'class' => 'shiyan-sjc', 'table' => 'shiyan_sjc', 'table_name' => '实验室检查'),
      'template' => 'templates/shiyan_sjc',
    ),
    'crf_case_form_zq1_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq1-1', 'table' => 'zq1_1', 'table_name' => '研究给药'),
      'template' => 'templates/zq1_1',
    ),
    'crf_case_form_zq1_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq1-2', 'table' => 'zq1_2', 'table_name' => '伴随治疗'),
      'template' => 'templates/zq1_2',
    ),
    'crf_case_form_zq2_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq2_1', 'table_name' => '第一周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq2_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq2_2', 'table_name' => '第一周期研究治疗是否发生减量/或延迟用药？'),
      'template' => 'templates/zq_2',
    ),
    'crf_case_form_zq2_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq2_3', 'table_name' => '第二周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3',
    ),
    'crf_case_form_zq2_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq2_4', 'table_name' => '研究给药', 'no_1' => '第一周期给药记录', 'no_2' => '第二周期给药计划'),
      'template' => 'templates/zq_4',
    ),
    'crf_case_form_zq2_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-5', 'table' => 'zq2_5', 'table_name' => '伴随治疗', 'no_1' => '二'),
      'template' => 'templates/zq_5',
    ),
    'crf_case_form_zq3_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq3_1', 'table_name' => '第二周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq3_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq3_2', 'table_name' => '第二周期研究治疗是否发生减量/或延迟用药？'),
      'template' => 'templates/zq_2',
    ),
    'crf_case_form_zq3_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq3_3', 'table_name' => '第三周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3',
    ),
    'crf_case_form_zq3_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq3_4', 'table_name' => '研究给药', 'no_1' => '第二周期给药记录', 'no_2' => '第三周期给药计划'),
      'template' => 'templates/zq_4',
    ),
    'crf_case_form_zq3_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-5', 'table' => 'zq3_5', 'table_name' => '伴随治疗', 'no_1' => '三'),
      'template' => 'templates/zq_5',
    ),
    'crf_case_form_zq4_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq4_1', 'table_name' => '第三周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq4_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq4_2', 'table_name' => '第三周期研究治疗是否发生减量/或延迟用药？'),
      'template' => 'templates/zq_2',
    ),
    'crf_case_form_zq4_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq4_3', 'table_name' => '第四周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3',
    ),
    'crf_case_form_zq4_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq4_4', 'table_name' => '研究给药', 'no_1' => '第三周期给药记录', 'no_2' => '第四周期给药计划'),
      'template' => 'templates/zq_4',
    ),
    'crf_case_form_zq4_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-5', 'table' => 'zq4_5', 'table_name' => '伴随治疗', 'no_1' => '四'),
      'template' => 'templates/zq_5',
    ),
    'crf_case_form_zq5_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq5_1', 'table_name' => '第四周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq5_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq5_2', 'table_name' => '第四周期研究治疗是否发生减量/或延迟用药？'),
      'template' => 'templates/zq_2',
    ),
    'crf_case_form_zq5_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq5_3', 'table_name' => '第五周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3',
    ),
    'crf_case_form_zq5_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq5_4', 'table_name' => '研究给药', 'no_1' => '第四周期给药记录', 'no_2' => '第五周期给药计划'),
      'template' => 'templates/zq_4',
    ),
    'crf_case_form_zq5_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-5', 'table' => 'zq5_5', 'table_name' => '伴随治疗', 'no_1' => '五'),
      'template' => 'templates/zq_5',
    ),
    'crf_case_form_zq6_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq6_1', 'table_name' => '第五周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq6_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq6_2', 'table_name' => '第五周期研究治疗是否发生减量/或延迟用药？'),
      'template' => 'templates/zq_2',
    ),
    'crf_case_form_zq6_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq6_3', 'table_name' => '第六周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3',
    ),
    'crf_case_form_zq6_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq6_4', 'table_name' => '研究给药', 'no_1' => '第五周期给药记录', 'no_2' => '第六周期给药计划'),
      'template' => 'templates/zq_4',
    ),
    'crf_case_form_zq6_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-5', 'table' => 'zq6_5', 'table_name' => '伴随治疗', 'no_1' => '六'),
      'template' => 'templates/zq_5',
    ),
    'crf_case_form_zq7_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq7_1', 'table_name' => '第六周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq7_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq7_2', 'table_name' => '第六周期研究治疗是否发生减量/或延迟用药？'),
      'template' => 'templates/zq_2',
    ),
    'crf_case_form_zq7_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq7_3', 'table_name' => '第七周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3',
    ),
    'crf_case_form_zq7_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq7_4', 'table_name' => '研究给药', 'no_1' => '第六周期给药记录', 'no_2' => '第七周期给药计划'),
      'template' => 'templates/zq_4',
    ),
    'crf_case_form_zq7_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-5', 'table' => 'zq7_5', 'table_name' => '伴随治疗', 'no_1' => '七'),
      'template' => 'templates/zq_5',
    ),
    'crf_case_form_zq8_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq8_1', 'table_name' => '第七周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq8_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq8_2', 'table_name' => '第八周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq8_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq8_3', 'table_name' => '研究给药', 'no_1' => '七', 'no_2' => '八'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq8_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq8_4', 'table_name' => '伴随治疗', 'no_1' => '八'),
      'template' => 'templates/zq_n_4',
    ),
    'crf_case_form_zq9_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq9_1', 'table_name' => '第八周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq9_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq9_2', 'table_name' => '第九周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq9_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq9_3', 'table_name' => '研究给药', 'no_1' => '八', 'no_2' => '九'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq9_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq9_4', 'table_name' => '伴随治疗', 'no_1' => '九'),
      'template' => 'templates/zq_n_4',
    ),
    'crf_case_form_zq10_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq10_1', 'table_name' => '第九周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq10_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq10_2', 'table_name' => '第十周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq10_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq10_3', 'table_name' => '研究给药', 'no_1' => '九', 'no_2' => '十'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq10_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq10_4', 'table_name' => '伴随治疗', 'no_1' => '十'),
      'template' => 'templates/zq_n_4',
    ),
    'crf_case_form_zq11_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq11_1', 'table_name' => '第十周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq11_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq11_2', 'table_name' => '第十一周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq11_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq11_3', 'table_name' => '研究给药', 'no_1' => '十', 'no_2' => '十一'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq11_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq11_4', 'table_name' => '伴随治疗', 'no_1' => '十一'),
      'template' => 'templates/zq_n_4',
    ),
   'crf_case_form_zq12_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq12_1', 'table_name' => '第十一周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq12_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq12_2', 'table_name' => '第十二周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq12_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq12_3', 'table_name' => '研究给药', 'no_1' => '十一', 'no_2' => '十二'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq12_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq12_4', 'table_name' => '伴随治疗', 'no_1' => '十二'),
      'template' => 'templates/zq_n_4',
    ),
   'crf_case_form_zq13_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq13_1', 'table_name' => '第十二周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq13_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq13_2', 'table_name' => '第十三周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq13_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq13_3', 'table_name' => '研究给药', 'no_1' => '十二', 'no_2' => '十三'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq13_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq13_4', 'table_name' => '伴随治疗', 'no_1' => '十三'),
      'template' => 'templates/zq_n_4',
    ),
   'crf_case_form_zq14_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq14_1', 'table_name' => '第十三周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq14_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq14_2', 'table_name' => '第十四周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq14_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq14_3', 'table_name' => '研究给药', 'no_1' => '十三', 'no_2' => '十四'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq14_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq14_4', 'table_name' => '伴随治疗', 'no_1' => '十四'),
      'template' => 'templates/zq_n_4',
    ),
   'crf_case_form_zq15_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq15_1', 'table_name' => '第十四周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq15_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq15_2', 'table_name' => '第十五周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq15_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq15_3', 'table_name' => '研究给药', 'no_1' => '十四', 'no_2' => '十五'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq15_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq15_4', 'table_name' => '伴随治疗', 'no_1' => '十五'),
      'template' => 'templates/zq_n_4',
    ),
   'crf_case_form_zq16_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-1', 'table' => 'zq16_1', 'table_name' => '第十五周期化疗不良事件'),
      'template' => 'templates/zq_1',
    ),
    'crf_case_form_zq16_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-2', 'table' => 'zq16_2', 'table_name' => '第十六周期化疗前主要实验室检查结果'),
      'template' => 'templates/zq_3', //special
    ),
    'crf_case_form_zq16_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-3', 'table' => 'zq16_3', 'table_name' => '研究给药', 'no_1' => '十五', 'no_2' => '十六'),
      'template' => 'templates/zq_n_3',
    ),
    'crf_case_form_zq16_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'zq-4', 'table' => 'zq16_4', 'table_name' => '伴随治疗', 'no_1' => '十六'),
      'template' => 'templates/zq_n_4',
    ),
    'crf_case_form_zhiliao_js' => array(
      'arguments' => array('form' => NULL, 'class' => 'zhiliao-js', 'table' => 'zhiliao_js', 'table_name' => '治疗结束'),
      'template' => 'templates/zhiliao_js',
    ),
    'crf_case_form_xueye_zlbjwjcjghzb' => array(
      'arguments' => array('form' => NULL, 'class' => 'xueye-zlbjwjcjghzb', 'table' => 'xueye_zlbjwjcjghzb', 'table_name' => '血液肿瘤标记物检测结果汇总表'),
      'template' => 'templates/xueye_zlbjwjcjghzb',
    ),        
    'crf_case_form_yanzhong_blsjjl' => array(
      'arguments' => array('form' => NULL, 'class' => 'yanzhong-blsjjl', 'table' => 'yanzhong_blsjjl', 'table_name' => '严重不良事件记录'),
      'template' => 'templates/yanzhong_blsjjl',
    ),  
    'crf_case_form_yanzhong_blsjjl_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'yanzhong-blsjjl', 'table' => 'yanzhong_blsjjl_1', 'table_name' => '严重不良事件记录'),
      'template' => 'templates/yanzhong_blsjjl',
    ), 
    'crf_case_form_pg1_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg1-1', 'table' => 'pg1_1', 'table_name' => '体格检查'),
      'template' => 'templates/pg_1',
    ), 
    'crf_case_form_pg1_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg1-2', 'table' => 'pg1_2', 'table_name' => '心电图检查'),
      'template' => 'templates/pg_2',
    ),    
    'crf_case_form_pg1_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg1-3', 'table' => 'pg1_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/pg_3',
    ),
    'crf_case_form_pg1_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg1-4', 'table' => 'pg1_4', 'table_name' => '血液肿瘤标记物检测'),
      'template' => 'templates/pg_4',
    ), 
    'crf_case_form_pg1_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg1-5', 'table' => 'pg1_5', 'table_name' => '肿瘤是否进展/复发/转移？'),
      'template' => 'templates/pg_5',
    ),    
    'crf_case_form_pg1_6' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg1-6', 'table' => 'pg1_6', 'table_name' => '实验室检查'),
      'template' => 'templates/pg_6',
    ),
    'crf_case_form_pg2_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg2-1', 'table' => 'pg2_1', 'table_name' => '体格检查'),
      'template' => 'templates/pg_1',
    ), 
    'crf_case_form_pg2_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg2-2', 'table' => 'pg2_2', 'table_name' => '心电图检查'),
      'template' => 'templates/pg_2',
    ),    
    'crf_case_form_pg2_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg2-3', 'table' => 'pg2_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/pg_3',
    ),
    'crf_case_form_pg2_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg2-4', 'table' => 'pg2_4', 'table_name' => '血液肿瘤标记物检测'),
      'template' => 'templates/pg_4',
    ), 
    'crf_case_form_pg2_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg2-5', 'table' => 'pg2_5', 'table_name' => '肿瘤是否进展/复发/转移？'),
      'template' => 'templates/pg_5',
    ),    
    'crf_case_form_pg2_6' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg2-6', 'table' => 'pg2_6', 'table_name' => '实验室检查'),
      'template' => 'templates/pg_6',
    ),
    'crf_case_form_pg3_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg3-1', 'table' => 'pg3_1', 'table_name' => '体格检查'),
      'template' => 'templates/pg_1',
    ), 
    'crf_case_form_pg3_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg3-2', 'table' => 'pg3_2', 'table_name' => '心电图检查'),
      'template' => 'templates/pg_2',
    ),    
    'crf_case_form_pg3_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg3-3', 'table' => 'pg3_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/pg_3',
    ),
    'crf_case_form_pg3_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg3-4', 'table' => 'pg3_4', 'table_name' => '血液肿瘤标记物检测'),
      'template' => 'templates/pg_4',
    ), 
    'crf_case_form_pg3_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg3-5', 'table' => 'pg3_5', 'table_name' => '肿瘤是否进展/复发/转移？'),
      'template' => 'templates/pg_5',
    ),    
    'crf_case_form_pg3_6' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg3-6', 'table' => 'pg3_6', 'table_name' => '实验室检查'),
      'template' => 'templates/pg_6',
    ),
    'crf_case_form_pg4_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg4-1', 'table' => 'pg4_1', 'table_name' => '体格检查'),
      'template' => 'templates/pg_1',
    ), 
    'crf_case_form_pg4_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg4-2', 'table' => 'pg4_2', 'table_name' => '心电图检查'),
      'template' => 'templates/pg_2',
    ),    
    'crf_case_form_pg4_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg4-3', 'table' => 'pg4_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/pg_3',
    ),
    'crf_case_form_pg4_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg4-4', 'table' => 'pg4_4', 'table_name' => '血液肿瘤标记物检测'),
      'template' => 'templates/pg_4',
    ), 
    'crf_case_form_pg4_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg4-5', 'table' => 'pg4_5', 'table_name' => '肿瘤是否进展/复发/转移？'),
      'template' => 'templates/pg_5',
    ),    
    'crf_case_form_pg4_6' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg4-6', 'table' => 'pg4_6', 'table_name' => '实验室检查'),
      'template' => 'templates/pg_6',
    ),
    'crf_case_form_pg5_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg5-1', 'table' => 'pg5_1', 'table_name' => '体格检查'),
      'template' => 'templates/pg_1',
    ), 
    'crf_case_form_pg5_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg5-2', 'table' => 'pg5_2', 'table_name' => '心电图检查'),
      'template' => 'templates/pg_2',
    ),    
    'crf_case_form_pg5_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg5-3', 'table' => 'pg5_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/pg_3',
    ),
    'crf_case_form_pg5_4' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg5-4', 'table' => 'pg5_4', 'table_name' => '血液肿瘤标记物检测'),
      'template' => 'templates/pg_4',
    ), 
    'crf_case_form_pg5_5' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg5-5', 'table' => 'pg5_5', 'table_name' => '肿瘤是否进展/复发/转移？'),
      'template' => 'templates/pg_5',
    ),    
    'crf_case_form_pg5_6' => array(
      'arguments' => array('form' => NULL, 'class' => 'pg5-6', 'table' => 'pg5_6', 'table_name' => '实验室检查'),
      'template' => 'templates/pg_6',
    ),
    'crf_case_form_sf1_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf1-1', 'table' => 'sf1_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf1_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf1-2', 'table' => 'sf1_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf1_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf1-3', 'table' => 'sf1_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf2_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf2-1', 'table' => 'sf2_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf2_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf2-2', 'table' => 'sf2_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf2_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf2-3', 'table' => 'sf2_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf3_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf3-1', 'table' => 'sf3_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf3_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf3-2', 'table' => 'sf3_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf3_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf3-3', 'table' => 'sf3_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf4_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf4-1', 'table' => 'sf4_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf4_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf4-2', 'table' => 'sf4_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf4_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf4-3', 'table' => 'sf4_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf5_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf5-1', 'table' => 'sf5_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf5_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf5-2', 'table' => 'sf5_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf5_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf5-3', 'table' => 'sf5_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf6_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf6-1', 'table' => 'sf6_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf6_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf6-2', 'table' => 'sf6_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf6_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf6-3', 'table' => 'sf6_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf7_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf7-1', 'table' => 'sf7_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf7_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf7-2', 'table' => 'sf7_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf7_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf7-3', 'table' => 'sf7_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf8_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf8-1', 'table' => 'sf8_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf8_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf8-2', 'table' => 'sf8_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf8_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf8-3', 'table' => 'sf8_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_sf9_1' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf9-1', 'table' => 'sf9_1', 'table_name' => '患者状态'),
      'template' => 'templates/sf_1',
    ), 
    'crf_case_form_sf9_2' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf9-2', 'table' => 'sf9_2', 'table_name' => '疾病状况'),
      'template' => 'templates/sf_2',
    ), 
    'crf_case_form_sf9_3' => array(
      'arguments' => array('form' => NULL, 'class' => 'sf9-3', 'table' => 'sf9_3', 'table_name' => '肿瘤评估'),
      'template' => 'templates/sf_3',
    ), 
    'crf_case_form_siwang_jl' => array(
      'arguments' => array('form' => NULL, 'class' => 'siwang-jl', 'table' => 'siwang_jl', 'table_name' => '死亡记录'),
      'template' => 'templates/siwang_jl',
    ), 
    'crf_case_form_yanjiu_js' => array(
      'arguments' => array('form' => NULL, 'class' => 'yanjiu-js', 'table' => 'yanjiu_js', 'table_name' => '研究结束'),
      'template' => 'templates/yanjiu_js',
    ), 
  );
}

