<?php

/**
* Implementation of hook_menu
*/
function crf_case_menu()
{
  $items = array();
  $items['crf_case/%/%'] = array(
    'page callback' => 'crf_case',
    'page arguments' => array(1,2),
    'access callback' => 'crf_case_perm',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK
  );
  $items['crf_case_edit'] = array(
    'page callback' => 'crf_case_edit',
    'access callback' => 'crf_case_perm',
    'type' => MENU_CALLBACK
  );
  return $items;  
}

function crf_case_perm() {
  global $user;
  if ((isset($user->roles[3]) || $user->uid == 1)) {
    return true;
  }
  else {
    return false;
  }
}

function crf_case($p_uid, $type) {
  global $user;
  $hospital_no = $user->profile_hospital_no;
  $hospital_name = $user->profile_hospital_name;
  $query = "SELECT p_uid FROM apply WHERE p_uid = %d AND hospital_no = '%s' AND hospital_name = '%s'";
  if (db_result(db_query($query, $p_uid, $hospital_no, $hospital_name))) {
    crf_common_session('p_uid', $p_uid);
    crf_common_session('type', $type); //1代表可编辑 2代表不可编辑
    drupal_goto('crf_case_edit');
  }
  else {
    drupal_set_message('非法操作，请从下列列表中选择一项进入录入!');
    drupal_goto('crf_case');
  }
}
/**
 * 参数eg:
 * crf_case_edit/no
 * crf_case_edit/第几页
 */
function crf_case_edit() {
  $no = arg(1);
  if (empty($no)) {
    drupal_goto('crf_case_edit/1');
  }
  return drupal_get_form("crf_case_form", $no);
}

function crf_case_form(&$form_state, $arg = NULL) {
  $no = $arg;
  module_load_include('inc', 'crf_case', 'form_elements'); 
  $form_elements_arr = get_form_elements_arr($no);
  foreach($form_elements_arr as $row => $group) {
    foreach($group as $element_no => $element) {
//      print "e_{$no}_{$row}_{$element_no}";
      $form["e_{$no}_{$row}_{$element_no}"] = $element;
    }
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value'=> '确定'
  );
  return $form;
}