<?php

/**
* Implementation of hook_menu
*/
function crf_common_menu()
{
  $items = array();
  $items['crf_front'] = array(
    'title' => 'Front',
    'page callback' => 'crf_common_front',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;  
}

/**
 * Menu callback; Generate a listing of promoted nodes.
 */
function crf_common_front() {
  global $user;
  if ($user->uid) {
    drupal_goto('user');
  }
  else {
    drupal_set_title('');
    $output = drupal_get_form('user_login_block');    
  }
  return $output;
}